#!/bin/bash

#PBS -l walltime=10:00:00,select=1:ncpus=4:mem=6gb
#PBS -N <job name>
#PBS -A st-caw42-1
#PBS -m abe
#PBS -M <your email address>
#PBS -o /scratch/st-caw42-1/model_output.txt
#PBS -e /scratch/st-caw42-1/model_errors.txt
 
################################################################################

module load gcc/9.1.0
module load python/3.7.3

cd /arc/project/st-caw42-1
source cmdstanpy_env/bin/activate

python <name of .py file>

